services:
  next-js:
    build:
      dockerfile: docker/next/Dockerfile
      context: .
    volumes:
      - '.:/var/www'
      - '/var/www/node_modules'
    ports:
      - '${APP_PORT:-3000}:3000'
    networks:
      - next-js-kit

networks:
  next-js-kit:
    driver: bridge
