name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
      - main

jobs:
  build:
    environment: ${{ github.event_name == 'pull_request' && 'Preview' || github.ref == 'refs/heads/develop' && 'Development' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project dependencies
        run: npm install

      - name: Start Next.js server
        run: npm run dev & sleep 5

      - name: Build the project
        run: npm run build