name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install the project dependencies
        run: npm ci

      - name: Fix code style issues with prettier & eslint
        run: npm run lint:fix && npm run prettier:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling

  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: env setting
        run: |
          touch .env
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.APP_API_URL }}" >> .env
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.APP_API_URL }}

      - name: Install the project dependencies
        run: rm -rf node_modules && npm ci

      - name: Build the project
        run: npm run build

      - name: Start Next.js server
        run: npm run start & sleep 5

      - name: Build the project
        run: npm run build
